Author: Gup

Practicing Neural Network Implementation on very simple case of identifying B+ or B- mesons from

$B^{\pm}\rightarrow K^{\pm}K^{+}K^{-}$

based on given kaon charge data

In [275]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras import layers
import glob

In [153]:
%pip install tensorflow
%pip install keras

^C
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [276]:
files = []
eventData = []

list_of_files = glob.glob('**/*.csv', recursive=True)
for i in list_of_files:
    files.append(i)

files

['ignore\\B2KKK_MagnetDown.csv', 'ignore\\B2KKK_MagnetUp.csv']

In [277]:
column_names = ["B_FlightDistance", "B_VertexChi2", "H1_PX", "H1_PY", "H1_PZ", "H1_ProbK", "H1_ProbPi", "H1_Charge", "H1_IPChi2", 
"H2_PX", "H2_PY", "H2_PZ", "H2_ProbK", "H2_ProbPi", "H2_Charge", "H2_IPChi2", 
"H3_PX", "H3_PY", "H3_PZ", "H3_ProbK", "H3_ProbPi", "H3_Charge", "H3_IPChi2"]

# Read the CSV file and assign the column names from the first ro
df1 = pd.read_csv("ignore/B2KKK_MagnetUp.csv", header = None, names = column_names, on_bad_lines = "skip", engine = "python", comment = "#")

df2 = pd.read_csv("ignore/B2KKK_MagnetDown.csv", header = None, names = column_names, on_bad_lines = "skip", engine = "python", comment = "#")

df = pd.concat([df1, df2], ignore_index=True)
df

B_FlightDistance  B_VertexChi2     H1_PX      H1_PY    H1_PZ  H1_ProbK  \
0              10.42810       4.05695 -4168.060  -704.9540  24548.8  0.771199   
1              33.59130       2.22024  1295.910   -61.9569  35569.6  0.932006   
2              16.53190      11.59340  1493.050  1944.6000  33003.9  0.953512   
3               4.10280      11.32170  -236.694   843.8090  28207.1  0.655129   
4               3.50935       5.73940   123.874   856.2900  51956.6  0.940484   
...                 ...           ...       ...        ...      ...       ...   
26954          31.09040       3.31873  -868.888  -429.5470  28948.2  0.724375   
26955           6.88156       3.87262   588.582   523.0460  17737.8  0.741060   
26956           6.27275      11.17060   392.544  1041.1900  15034.3  0.765920   
26957          24.39090       3.46987  -889.297   431.4790  14038.3  0.931028   
26958           6.20237       5.24702   497.978  -500.4530  17999.1  0.901493   

       H1_ProbPi  H1_Charge   H1_IPChi2     H2_PX  ...  H2_ProbPi  H2_Charge  \
0       0.051726         -1  1002.66000 -3393.640  ...   0.038719          1   
1       0.058690         -1  6672.09000   613.485  ...   0.043657          1   
2       0.104768         -1  1731.92000   373.614  ...   0.039157          1   
3       0.045339         -1     5.03376  -561.906  ...   0.040908          1   
4       0.078220         -1     7.00589   110.753  ...   0.041739          1   
...          ...        ...         ...       ...  ...        ...        ...   
26954   0.039420         -1  1349.73000 -1417.660  ...   0.056467          1   
26955   0.055822          1   214.29600  -484.077  ...   0.045518         -1   
26956   0.071357          1   233.88300 -1347.500  ...   0.025600         -1   
26957   0.055747         -1  7235.70000 -2258.700  ...   0.037033          1   
26958   0.126222         -1     3.65512  -959.742  ...   0.039556          1   

        H2_IPChi2    H3_PX     H3_PY    H3_PZ  H3_ProbK  H3_ProbPi  H3_Charge  \
0       714.17500 -8864.96 -7428.640  77446.2  0.934580   0.128720          1   
1       737.22000  -341.75  3317.420  24380.2  0.968883   0.129317          1   
2       499.99900  4779.03  -287.830  53908.5  0.844950   0.064803          1   
3         6.58870 -1085.33 -3076.760  30036.2  0.912293   0.080841          1   
4         2.09042  1640.00  2660.280  19441.3  0.702135   0.028641          1   
...           ...      ...       ...      ...       ...        ...        ...   
26954  1597.50000 -7141.53 -3904.320  83336.7  0.525309   0.129747          1   
26955    25.25580 -6479.90  1695.490  68440.2  0.957104   0.092155         -1   
26956  1859.50000 -4552.41  6281.470  75866.3  0.923278   0.064446         -1   
26957  5225.58000 -5104.51 -3882.280  39723.6  0.976290   0.164023          1   
26958  1806.52000  3324.62   226.161  19403.2  0.940421   0.046492          1   

        H3_IPChi2  
0        536.5850  
1      23332.5000  
2       3484.1900  
3        489.0470  
4        888.5350  
...           ...  
26954   3879.8800  
26955    434.4930  
26956     62.5421  
26957  17515.2000  
26958   1634.5300  

[26959 rows x 23 columns]

Calculate the B+ and B- by hand to train the neural net (redudant but it's for the sake of practice)

In [278]:
negativeCharges = 0
positiveCharges = 0

H1_Charge = np.array(df.loc[:,"H1_Charge"], dtype = float)
H2_Charge = np.array(df.loc[:,"H2_Charge"], dtype = float)
H3_Charge = np.array(df.loc[:,"H3_Charge"], dtype = float)

target_array = []
for i in range(len(H1_Charge)):
    if (H1_Charge[i] + H2_Charge[i] + H3_Charge[i] == 1):
        positiveCharges += 1
        target_array.append(1)
    if (H1_Charge[i] + H2_Charge[i] + H3_Charge[i] == -1):
        negativeCharges += 1
        target_array.append(-1)
        
print("$B^{+}$ decays =", positiveCharges)
print("$B^{-}$ decays =", negativeCharges)

A_global = (negativeCharges - positiveCharges) / (negativeCharges + positiveCharges)
print("A_global = ", A_global)

$B^{+}$ decays = 13957
$B^{-}$ decays = 13002
A_global =  -0.03542416261730776


In [279]:
df["target"] = df["H1_Charge"] + df["H2_Charge"] + df["H3_Charge"]


# df_norm = (df - df.min()) / (df.max() - df.min())
# df_norm
target = df.pop("target")

df.pop("B_FlightDistance")
df.pop("B_VertexChi2")
df.pop("H1_PX")
df.pop("H1_PY")
df.pop("H1_PZ")
df.pop("H1_ProbK")
df.pop("H1_ProbPi")
df.pop("H1_IPChi2")
df.pop("H2_PX")
df.pop("H2_PY")
df.pop("H2_PZ")
df.pop("H2_ProbPi")
df.pop("H2_IPChi2")
df.pop("H3_PX")
df.pop("H3_PY")
df.pop("H3_PZ")
df.pop("H3_ProbK")
df.pop("H3_ProbPi")
df.pop("H3_IPChi2")
df.pop("H2_ProbK")

0        0.917991
1        0.515930
2        0.868579
3        0.601544
4        0.920603
           ...   
26954    0.767277
26955    0.690964
26956    0.710365
26957    0.700289
26958    0.648200
Name: H2_ProbK, Length: 26959, dtype: float64

In [280]:
df

H1_Charge  H2_Charge  H3_Charge
0             -1          1          1
1             -1          1          1
2             -1          1          1
3             -1          1          1
4             -1          1          1
...          ...        ...        ...
26954         -1          1          1
26955          1         -1         -1
26956          1         -1         -1
26957         -1          1          1
26958         -1          1          1

[26959 rows x 3 columns]

Normalize using keras layer

In [304]:
normalizer = tf.keras.layers.Normalization(axis = -1)
normalizer.adapt(df)

Build the model, input is shape (.80 * 26959, 23, 1)

In [305]:
model = Sequential()
model.add(layers.InputLayer(input_shape = (3)))
model.add(Dense(2))
model.add(Activation("relu"))
model.add(Dense(1))

loss=tf.keras.losses.MeanSquaredError()
model.compile(loss= loss, optimizer= "adam", metrics= ["accuracy"])

model.summary()

Model: "sequential_37"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_70 (Dense)            (None, 2)                 8         
                                                                 
 activation_47 (Activation)  (None, 2)                 0         
                                                                 
 dense_71 (Dense)            (None, 1)                 3         
                                                                 
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________


In [306]:
numeric_features = tf.convert_to_tensor(df)
t = tf.convert_to_tensor(target)
t

numeric_features = numeric_features.numpy()
print(np.shape(numeric_features))
t = t.numpy().reshape(26959,1)
print(np.shape(t))

print(numeric_features)
print(t)

(26959, 3)
(26959, 1)
[[-1  1  1]
 [-1  1  1]
 [-1  1  1]
 ...
 [ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]]
[[ 1]
 [ 1]
 [ 1]
 ...
 [-1]
 [ 1]
 [ 1]]


In [307]:
model.fit(numeric_features, np.array(target_array), epochs=20, batch_size=32)

Epoch 1/20
843/843 [==============================] - 1s 685us/step - loss: 0.1546 - accuracy: 0.5177
Epoch 2/20
843/843 [==============================] - 1s 683us/step - loss: 5.3242e-10 - accuracy: 0.5177
Epoch 3/20
843/843 [==============================] - 1s 679us/step - loss: 1.0353e-13 - accuracy: 0.5177
Epoch 4/20
843/843 [==============================] - 1s 715us/step - loss: 3.9771e-14 - accuracy: 0.5177
Epoch 5/20
843/843 [==============================] - 1s 697us/step - loss: 1.5248e-14 - accuracy: 0.5177
Epoch 6/20
843/843 [==============================] - 1s 675us/step - loss: 1.1313e-14 - accuracy: 0.5177
Epoch 7/20
843/843 [==============================] - 1s 668us/step - loss: 8.8701e-15 - accuracy: 0.5177
Epoch 8/20
843/843 [==============================] - 1s 672us/step - loss: 7.3020e-16 - accuracy: 0.5177
Epoch 9/20
843/843 [==============================] - 1s 679us/step - loss: 0.0000e+00 - accuracy: 0.5177
Epoch 10/20
843/843 [=============================

In [308]:

model.predict([[1,6,-1]])

1/1 [==============================] - 0s 47ms/step


array([[-1.9834273]], dtype=float32)